### ISSUE TITLE
Update debian and ubuntu packages

### ISSUE THREAD

**Issue by droidmonkey** [nitroshare/qhttpengine#24]
Continuing the conversation here to see if we can move this along. As you stated previously since there is such a huge difference between 0.1 and 1.0 we would need to diverge the package as well. We can find a debian sponsor for you, the one who recommended we use your package would work. What is required to update the Ubuntu repos?

This issue supports integration with [KeePassXC](https://github.com/keepassxreboot/keepassxc/pull/1169)

**Comment by julian-klode** [comment]
The Ubuntu package is synced from Debian. I'm happy to sponsor uploads to Debian, just upload them to mentors and I can grab them, check them and build and upload them; or report back with a TODO list.

**Comment by nathan-osman** [comment]
Sorry for the delay in getting back to you - somehow this slipped through my inbox.

The changes between 0.1 and 1.0 are backwards-incompatible, as already noted above. Should I change the source package name to reflect this when I upload to mentors? The binary package already has the major version suffix (`libqhttpengine0`). But the source package has no such suffix.

**Comment by julian-klode** [comment]
Well, it makes no sense to rename the source package when it shares binary packages like libqhttpengine-dev. If you want people to be able to build against two different versions, you'd have to rename the binaries too.

I suggest you consider how often you want to change API, and if there are multiple changes planned, you might want to rename the -dev binary and add an API tag in there. you could have like libqhttpengine-1.so.0, giving you libqhttpengine-1-0 and libqhttp-1-dev, where 1 is the API and 0 is the ABI.

**Comment by nathan-osman** [comment]
> Well, it makes no sense to rename the source package when it shares binary packages like libqhttpengine-dev.

Oh right - good point. So regardless of what I do, the binary packages will need new names:

- `libqhttpengine-1-dev`
- `libqhttpengine-1-doc`
- `libqhttpengine-1-examples`
- `libqhttpengine-1-1`

(Both the API and ABI have changed, unfortunately.)

It will still be impossible to install both versions of the `-dev` package since there would be a number of files with identical paths (`/usr/include/qhttpengine/*`, `/usr/lib/x86_64-linux-gnu/cmake/*`, etc.). I can either:

1. let it be impossible to have both versions of some binary packages installed
2. add a patch (with Quilt) to rewrite the filenames before installation (very difficult)

What would you recommend?

**Comment by julian-klode** [comment]
Well, if you don't change the paths too (basically qhttpengine-1 would be a different library from qhttpengine-2 then, you'd have include/qhhtpengine-1, FindQHttpEngine1, and so on), then it makes no sense to have an extra API level in the package name. But that's OK, a lot of libraries do not include an API name.

**Comment by nathan-osman** [comment]
Sorry again for the delay. Here is the upload in mentors: https://mentors.debian.net/package/qhttpengine

**Comment by droidmonkey** [comment]
Howdy, what's the status on the Debian update to 1.01?

**Comment by nathan-osman** [comment]
Just waiting for a sponsor to upload it from mentors.

**Comment by tillea** [comment]
Hi,
I was made aware about this issue by Nicolas Schodet <nico@ni.fr.eu.org> who is volunteering to serve as Uploader for this package inside Debian.  Nicolas became aware about this package when I filed an [Intend to Salvage bug](https://bugs.debian.org/1120099) without checking here - sorry about this.
Just lets make something sensible out of this.  I'll happily support maintaining the Debian packaging on salsa.debian.org - just lets find out what might be the most convenient solution for you.
Kind regards, Andreas.

**Comment by droidmonkey** [comment]
This project is largely overcome by events with qt6

**Comment by tillea** [comment]
Thank you for your fast response.
In other words would you recommend removing the package from Debian?  If so I would turn the bug above into a request for removal.

**Comment by nathan-osman** [comment]
Jumping in quickly here: this project made a lot more sense in Qt 5. Although it should compile for Qt 6, QtHttpServer largely provides the same functionality. 

QHttpEngine offers a few extras but as far as I'm concerned, this project is only receiving security fixes from me since I am too busy with other projects.
